packaging_format = 2

id = "grafana"
name = "Grafana"
description.en = "Metric & analytic dashboards for monitoring"
description.fr = "Tableaux de bord de supervision"

version = "10.1.5~ynh1"

maintainers = ["JimboJoe"]

[upstream]
license = "AGPL-3.0-only"
website = "https://grafana.com/"
demo = "https://play.grafana.org"
code = "https://github.com/grafana/grafana"

[integration]
yunohost = ">= 11.2"
architectures = "all"
multi_instance = false
ldap = false
sso = false
disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/grafana"

    [install.init_main_permission]
    type = "group"
    default = false

    [install.admin]
    type = "user"

[resources]
    [resources.system_user]

    [resources.install_dir]

    [resources.ports]

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages = "mariadb-server, influxdb"

        [[resources.apt.extras]]
        repo = "deb https://packages.grafana.com/oss/deb stable main"
        key = "https://packages.grafana.com/gpg.key"
        packages = "grafana"

    [resources.database]
    type = "mysql"
